spring.application.name=chatbot-bakend

# Spring AI - Ollama 模型調度中心
# 指向你的 Docker Ollama 位址
spring.ai.ollama.base-url=http://localhost:11434

# 必須跟你在 docker exec 跑的名字一模一樣
#spring.ai.ollama.chat.model=product-expert
 spring.ai.ollama.chat.model=deepseek-r1:7b

# (選填) 設定推論參數，例如: 溫度 (Temperature)
spring.ai.ollama.chat.options.temperature=0.3
spring.ai.ollama.chat.options.num-predict=8192
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.options.max-tokens=8192
spring.ai.ollama.chat.options.num-ctx=8192


# 向量資料庫檢索設定 (PGVector)
app.vectorstore.pgvector.dimensions=768
app.vectorstore.pgvector.index-type=HNSW
app.vectorstore.pgvector.distance-type=COSINE
app.vectorstore.pgvector.initialize-schema=true


# 關聯式資料庫與 JPA (PostgreSQL + PGVector)
spring.datasource.url=jdbc:postgresql://localhost:5432/virgo_rag_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 短期記憶與快取 (Redis)
# Redis 連線設定
spring.data.redis.host=localhost
spring.data.redis.port=6379

# (選填) 啟用連線池設定
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8

### Gemini 配置 ###

# 要綁信用卡，不然應該就是 409 了
# https://aistudio.google.com/prompts/new_chat

# 1. 填入你的 API Key
# 註. 一分鐘不能超過15次，不然要收錢
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
# 2. 指定模型
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
# 3. 指定溫度 (可選)
spring.ai.google.genai.chat.options.temperature=0.2